version = 1

# .uid files are machine-generated and must be checked in but do not involve any
# creative work.
[[annotations]]
path = [
    "addons/**/*.uid",
    "scenes/**/*.uid",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Godot resource files are creative works, but cannot contain copyright or
# license headers. Comments are supported, but will be discarded by the editor
# when saving changes to these files.
[[annotations]]
path = [
    "addons/git_lfs_checker/plugin.cfg",
    "addons/sprite_frames_exported_textures/plugin.cfg",
    "addons/storyquest_bootstrap/plugin.cfg",
    "addons/storyquest_bootstrap/*.tscn",
    "addons/threadbare_project_settings/plugin.cfg",
    "scenes/*.tscn",
    "scenes/**/*.tscn",
    "scenes/**/*.tres",
    # .import files are largely machine-generated but developers can tweak their contents
    "**/*.import",
    "default_bus_layout.tres",
    "export_presets.cfg",
    "project.godot",
]
SPDX-FileCopyrightText = "The Threadbare Authors"
SPDX-License-Identifier = "MPL-2.0"


[[annotations]]
path = "addons/dialogue_manager/**"
SPDX-FileCopyrightText = "2022-present Nathan Hoad and Dialogue Manager contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "addons/git_describe/**"
SPDX-FileCopyrightText = "Joseph Michael Ware (zibetnu)"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "assets/third_party/xylophone-sampler-pack/*.ogg"
SPDX-FileCopyrightText = "2013 juancamiloorjuela"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "assets/third_party/tiny-swords/**/*.png",
    "assets/third_party/tiny-swords/**/*.aseprite",
]
SPDX-FileCopyrightText = "Pixel Frog"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "assets/first_party/**/*.aseprite",
    "assets/first_party/**/*.png",
    "assets/first_party/**/*.ogg",
    "assets/first_party/**/*.mp3",
    "icon-256.png",
    "icon.aseprite",
    "icon.png",
    "scenes/**/*.png",
    "scenes/**/*.svg",
    "scenes/**/*.aseprite",
]
SPDX-FileCopyrightText = "The Threadbare Authors"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "assets/third_party/inputs/keyboard-and-mouse/Blanks/*.png",
    "assets/third_party/inputs/keyboard-and-mouse/Dark/*.png",
    "assets/third_party/inputs/keyboard-and-mouse/Light/*.png",
]
SPDX-FileCopyrightText = "Nicolae (XELU) Berbece"
SPDX-License-Identifier = "CC0-1.0"
