# SPDX-FileCopyrightText: The Threadbare Authors
# SPDX-License-Identifier: MPL-2.0
name: Bug
description: An unexpected problem or behavior
labels: bug
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file an issue! **Please provide as much
        detail as you can** so we can properly confirm, triage, and fix your bug.

  - type: textarea
    id: about
    attributes:
      label: Description
      description: |
        Describe the bug you're seeing. Provide detail such as **where in the
        game** you experienced it and **what you were doing** in the game when
        it happened. If you can make it happen reliably, **share the steps to
        reproduce it**. If possible, please attach screenshots or a short video
        clip of the bug.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure you've completed each step and reviewed the [code of conduct](https://github.com/Endless-Access-Community/.github/blob/main/CODE_OF_CONDUCT.md) before submitting
      options:
        - label: I've reviewed and agree to follow the code of conduct
          required: true
