# SPDX-FileCopyrightText: The Threadbare Authors
# SPDX-License-Identifier: MPL-2.0
contact_links:
  - name: Join the Discord
    url: https://discord.gg/mNtzvvaFXF
    about: Chat with the team in real-time
