# SPDX-FileCopyrightText: The Threadbare Authors
# SPDX-License-Identifier: MPL-2.0
contact_links:
  - name: Playtest feedback
    about: Tell us about your experience playing Threadbare
    url: https://github.com/endlessm/threadbare/discussions/categories/playtest-feedback

  - name: Ask a question
    about: See previously-asked questions and ask your own
    url: https://github.com/endlessm/threadbare/discussions/categories/q-a

  - name: Join the Discord
    about: Chat with the team in real-time
    url: https://discord.gg/mNtzvvaFXF
