version = 1

[[annotations]]
path = [
	"*__tommylistens__bubble_*.wav",
]
SPDX-FileCopyrightText = "Copyright 2025 TommyListens <https://freesound.org/people/TommyListens/packs/44892/>"
SPDX-License-Identifier = "CC0-1.0"
