version = 1

[[annotations]]
path = [
	"crystal stone (1).png",
	"oldstone (1).png",
	"stone (1).png",
	"underwaterstone.png",
]
SPDX-FileCopyrightText = [
	"2018 Melissa Krautheim"
]
SPDX-License-Identifier = "CC0-1.0"
# https://opengameart.org/content/handpainted-stone-texture
